### ISSUE TITLE
FB7 does not support MODP-based Diffie-Hellman

### ISSUE THREAD

**Issue by hyperlumic** [fuzzball-muck/fuzzball#197] opened 2017-12-25 15:24 UTC
Testing has revealed that FB7 supports ECDH key agreement, but not traditional modulo-based DH key agreement. While ECDH is superior in many aspects, it's entirely possible (perhaps even likely) that some TLS v1.0-only clients support DH while lacking support for ECDH. Enabling this support might go a long way toward eventually being able to disable the (now deprecated/insecure) RSA encryption-based cipher modes.

Tested using tf5.0b8 on CentOS 7.

Configured a test MUCK using the following SSL preference: 
`aRSA+EECDH+AESGCM:aRSA+EDH+AESGCM:aRSA+EECDH+AES+SHA384:aRSA+EECDH+AES+SHA256:aRSA+EDH+AES+SHA384:aRSA+EDH+AES+SHA256:aRSA+EECDH+AES+SHA1:aRSA+EDH+AES+SHA1:aRSA+AESGCM:aRSA+AES+SHA384:aRSA+AES+SHA256:aRSA+AES+SHA1:!SRP:!PSK`

`$ openssl ciphers 'aRSA+EECDH+AESGCM:aRSA+EDH+AESGCM:aRSA+EECDH+AES+SHA384:aRSA+EECDH+AES+SHA256:aRSA+EDH+AES+SHA384:aRSA+EDH+AES+SHA256:aRSA+EECDH+AES+SHA1:aRSA+EDH+AES+SHA1:aRSA+AESGCM:aRSA+AES+SHA384:aRSA+AES+SHA256:aRSA+AES+SHA1:!SRP:!PSK' | tr ':' '\n'`

> ECDHE-RSA-AES256-GCM-SHA384
> ECDHE-RSA-AES128-GCM-SHA256
> DHE-RSA-AES256-GCM-SHA384
> DHE-RSA-AES128-GCM-SHA256
> ECDHE-RSA-AES256-SHA384
> ECDHE-RSA-AES128-SHA256
> DHE-RSA-AES256-SHA256
> DHE-RSA-AES128-SHA256
> ECDHE-RSA-AES256-SHA
> ECDHE-RSA-AES128-SHA
> DHE-RSA-AES256-SHA
> DHE-RSA-AES128-SHA
> AES256-GCM-SHA384
> AES128-GCM-SHA256
> AES256-SHA256
> AES128-SHA256
> AES256-SHA
> AES128-SHA

Attempting to connect to the test MUCK succeeds using the `ECDHE-RSA-AES256-GCM-SHA384` cipher suite.

Appending `!EECDH` to the end of the cipher preferences string, restarting the MUCK, and reattempting the connection succeeds using the `AES256-GCM-SHA384` cipher suite, which is the highest-preference (obsolete) RSA encryption mode specified in the cipher preferences.

Performing the same tests against a web server causes tf to connect to the web server using the `DHE-RSA-AES256-GCM-SHA384` cipher suite, which is the legacy-but-still-secure MODP-based Diffie-Hellman key agreement mode.

**Comment by nyanster** [comment] 2017-12-26 09:19
> Tested using tf5.0b8 on CentOS 7.

I also use tinyfugue as my client, so I'm familiar with the fact that it honestly doesn't do so well with TLS, despite the fact that it CAN do them. I'd firmly recommend, when testing TLS stuff, to instead be using OpenBSD's netcat, which can do TLS connections as so: nc -c
https://man.openbsd.org/nc
It's also available in many GNU/Linux distributions as a package, and also available in the portable release of libressl.
It, unlike tinyfugue, verifies cert signatures, among other things. You can use the -T flag to modify how strict  it is. In any case, tinyfugue shouldn't be used for TLS testing even though it's a nice client for actual MUCKing.
For example, since HereLieMonsters has a self-signed certificate:
nc -c -T noverify muck.hereliemonsters.org 7777
connects. Using -cv instead of -c lets you see details about the TLS negotiation when you connect. Many more details than tinyfugue tells you.

**Comment by sypherspace** [comment] 2017-12-26 12:29
> I'm familiar with the fact that it honestly doesn't do so well with TLS
TinyFugue does just fine with TLS (up to and including TLS v1.2) when linked against OpenSSL.

> I'd firmly recommend, when testing TLS stuff, to instead be using OpenBSD's netcat...
Why? The same argument could be made for using openssl's s_client functionality. Literally anything that verifies which cipher suite is negotiated with the other end is suitable for purpose.

> It's also available in many...
Who cares?

> It, unlike tinyfugue, verifies cert signatures, among other things...
Again, who cares? The issue is about FB7 not supporting MODP Diffie-Hellman. I'm unaware of ANY MUCK client that verifies cert signatures, so why would that be of value here?

Please keep comments to something that actually helps move the issue forward, instead of creating meaningless noise. Thank you.

**Comment by woggle** [comment] 2017-12-26 14:37
The underlying cause is probably a lack of call to SSL_CTX_set_tmp_dh or SSL_CTX_set_tmp_dh_auto. I think I previously avoided doing this because I was concerned about Java 6 clients which would negotiate a DHE ciphersuite but then reject modp groups larger than 1024 bits, which we can probably stop caring about anymore.

**Comment by sypherspace** [comment] 2017-12-26 15:01
Think we could do an Apache-style solution and allow for the administrator to specify a PEM-format DH parameter group in the cert file? That would allow the admin to determine whether or not they want to support old clients (by specifying a 1024-bit MODP group, or something larger), and default to something sane (2048-bit, maybe) if one isn't given?

**Comment by woggle** [comment] 2017-12-26 16:25
With OpenSSL 1.1+, we probably should just call SSL_CTX_set_tmp_dh_auto, on the assumption that the OpenSSL maintainers will do the right thing.

For prior versions, a parameter file generated in the build process would probably be easiest.

**Comment by wyld-sw** [comment] 2018-02-01 15:45
I added the following to reconfigure_ssl:
~~~~
#if defined(SSL_CTX_set_dh_auto)
    if (ctx->config->dheparams == -1)
        SSL_CTX_set_dh_auto(new_ssl_ctx, 1);
    else if (ctx->config->dheparams == 1024)
        SSL_CTX_set_dh_auto(new_ssl_ctx, 2);
#endif
~~~~
Seems to work. Let me know if it's actually completely broken, or if there's a better way. I'll close this issue after a few days if we determine it's the right solution.

**Closed** 2018-06-05 20:20 UTC
