### ISSUE TITLE
Switch TLS certificates without restart/connection interruption?

### ISSUE THREAD

**Issue by zeropoint** [fuzzball-muck/fuzzball#307] opened 2019-02-07 17:39 UTC
Would it be possible to implement a feature whereby fbmuck reloads its TLS cert/key pair/bundle without terminating existing connections or restarting the fbmuck process? The note at compile time says that Lets Encrypt can be used, but those only have a 90-day validity. It would be ideal if some signal could be sent to fbmuck to trigger this reload, i.e. with a `certbot --deploy-hook`.

**Comment by zeropoint** [comment] 2019-02-07 18:11
On further checking, it looks like `@reconfiguressl` might already do this. Could we have a signal added to trigger that functionality from outside the MUCK?

**Comment by digitalcircuit** [comment] 2019-02-08 05:36
Many programs seem to use `SIGHUP` as the signal to reload configuration/certificates/etc.  fbmuck [already configures `SIGHUP` as ignored](https://github.com/fuzzball-muck/fuzzball/blob/28c9c7222c3b2d9f11b4fac3afe2aa4d4f77eb80/src/fbsignal.c#L83 ); perhaps that'd be a good starting place to automatically call `@reconfiguressl`?

**Comment by nyanster** [comment] 2019-02-08 06:40
> Many programs seem to use `SIGHUP` as the signal to reload configuration/certificates/etc. fbmuck [already configures `SIGHUP` as ignored](https://github.com/fuzzball-muck/fuzzball/blob/28c9c7222c3b2d9f11b4fac3afe2aa4d4f77eb80/src/fbsignal.c#L83); perhaps that'd be a good starting place to automatically call `@reconfiguressl`?

Why not use SIGUSR1 though?  Both SIGUSR1 and SIGUSR2 are currently unused, but also guaranteed to only be sent by users and never be sent by the OS.  Otherwise SIGUSR1 and SIGHUP behave the same both according to POSIX and according to fb's current behavior.
You are right though that _**many**_ daemons use SIGHUP, though.

**Comment by nyanster** [comment] 2019-02-08 06:48
To give a reason (albeit potentially minor) to not use SIGHUP, I plan to sometime add a nodaemonize/nofork option for testing and debugging fb, making it stay in the foreground.  If xterm or some other terminal was closed while fb was running in it in the foreground, fb would receive SIGHUP.
But, SIGHUP being common for historical reasons is a reason (albeit definitely minor) to use SIGHUP.

**Comment by digitalcircuit** [comment] 2019-02-08 07:05
That's a good point!

[The `systemd.service` documentation on `ExecReload`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecReload= ) has an example using `SIGHUP`, but allows for any signal (or any command, really).

I imagine any other system service could adopt, so… this comes down to expectations?  As long as *some* signal allows reloading, picking *which* signal is more a matter of preference.

There's an [informative discussion over on StackOverflow regarding `SIGHUP`](https://stackoverflow.com/questions/19052354/sighup-for-reloading-configuration ).  Inversely, [`conky` uses `SIGUSR1` to reload](http://conky.sourceforge.net/docs.html ), and `conky` offers a nodaemon/nofork mode.  However, conky also listens to `SIGHUP` (*at least in Ubuntu 16.04*).

### Options

1.  **Listen to `SIGUSR1` only, ignore `SIGHUP`**
    * :heavy_plus_sign: Straightforward
    * :heavy_minus_sign: Doesn't follow expectations for those who don't read the docs
2.  **Listen to `SIGUSR1` always, and `SIGHUP` if not daemonizing/forking**
    * :heavy_plus_sign: Follows expectations in most situations
    * :heavy_minus_sign: Adds additional complexity, possibly non-intuitive to change signals based on mode
3.  **Listen to `SIGHUP` only**
    * :heavy_plus_sign: Follows expectations
    * :heavy_minus_sign: Complicates development

*Other options may exist!*

With @nyanster 's intention, I'd lean towards option 1.  Perhaps fbmuck could ship an example `fbmuck.service`/etc init system files, to help point to proper use?

**Comment by nyanster** [comment] 2019-02-08 07:27
I like that Option 1.

I think option 2 itself is flawed, but something similar to it could work if people wanted it: always reconfigure when receiving SIGUSR1.  nodaemonize fb is killed by SIGHUP, all other (normal fb) reconfigures by SIGHUP.  I agree it's needlessly complex, though.

**Comment by nyanster** [comment] 2019-02-08 07:38
Interesting, that reference to conky.  Looking at their issues, they switched back to SIGHUP doing the default action: SIGHUP kills conky now rather than reloading config.
https://github.com/brndnmtthws/conky/pull/642
https://github.com/brndnmtthws/conky/issues/436

**Comment by wyld-sw** [comment] 2019-02-08 11:39
I think SIGUSR1 is used to print the online player list to the log file - though the comments say that the technique predates WHO, so we’re probably safe in using it.

**Comment by nyanster** [comment] 2019-02-08 12:22
Ah, I notice SIGUSR2 is used, rather than unused as I mentioned earlier.
https://github.com/fuzzball-muck/fuzzball/blob/master/include/config.h#L67
https://github.com/fuzzball-muck/fuzzball/blob/master/src/fbsignal.c#L248
The status dumper that uses SIGUSR1:
https://github.com/fuzzball-muck/fuzzball/blob/master/src/fbsignal.c#L188
https://github.com/fuzzball-muck/fuzzball/blob/master/src/fbsignal.c#L240

I am curious why SIGEMERG (using SIGUSR2) exists though, when there are many signals specifically aimed to make a program terminate.  The message sent to users about a potential loss of power is also very specific, especially for something that can't be changed in defaults.h or something.
And in the comments, "immediate clean shutdown" sounds like a job for SIGTERM.  SIGTERM is already used for something else though.
sig_emerg() and sig_shutdown() differ only by two lines of code, though other functions are called with more lines of code.

I've never read fb's logfiles before, but, I'll go test the results of sending different signals to fb right now.  One moment~

**Comment by wyld-sw** [comment] 2019-02-08 12:39
I merged in the request for SIGUSR2 fairly early on in my current role, and wish I had the foresight to come up with a more generic solution. I think there's still time for that though.

Calling reconfigure_ssl, possibly with some logging to mention it was via signal, seems to be a good idea.

**Comment by wyld-sw** [comment] 2019-02-08 12:44
As for the no fork capability, does the "--no-detach" option work? This used to be a compile flag, and we can build in multiple paths to this if necessary.

**Comment by nyanster** [comment] 2019-02-08 12:47
> As for the no fork capability, does the "--no-detach" option work? This used to be a compile flag, and we can build in multiple paths to this if necessary.

Oh, oops.  You're right, it works.  -nodetach is available and it looks like I won't need to implement anything. :D
Thank you. >w<
I'm curious to see what goes to stdout and what goes to stderr now, I'll also test this.

**Comment by nyanster** [comment] 2019-02-08 12:55
> I'm curious to see what goes to stdout and what goes to stderr now, I'll also test this.

Regardless of -nodetach or not, three files are used in the logs directory: commands, restarts, and status.
Without -nodetach, there's fbmuck and fbmuck.err too.
fbmuck.err has what I had on stderr.

**Comment by wyld-sw** [comment] 2019-02-08 13:00
It's probably straightforward to change the meaning of SIGHUP based on the value of no_detach_flag. This might be our best solution. Thoughts?

**Comment by nyanster** [comment] 2019-02-08 13:09
The result of SIGUSR1 is the following text in the `status` file:
> 2019-02-08T08:07:30: STATUS REPORT:
2019-02-08T08:07:30: PLAYING descriptor 8 player One(1) from host ::1(33379), idle 4 seconds.

This is what the status dump looks like.

**Comment by wyld-sw** [comment] 2019-02-08 13:11
Yeah, it's basically a Wizard WHO with some differences. I don't think it'll be missed.

**Comment by nyanster** [comment] 2019-02-08 13:22
Even in the `status` file, killing with TERM vs USR2 are very similar...  Though sig_emerg() (usr2) seems to dump twice.
With TERM sig_shutdown():
```
2019-02-08T08:15:32: SHUTDOWN: via SIGNAL
2019-02-08T08:15:32: DUMPING: /home/dogg/min/mod/fuzzy/game/data/std-db.new.#1#
2019-02-08T08:15:32: DUMPING: /home/dogg/min/mod/fuzzy/game/data/std-db.new.#1# (done)
```
With USR2 sig_emerg():
```
2019-02-08T08:16:40: DUMPING: /home/dogg/min/mod/fuzzy/game/data/std-db.new.#1#
2019-02-08T08:16:40: DUMPING: /home/dogg/min/mod/fuzzy/game/data/std-db.new.#1# (done)
2019-02-08T08:16:40: DUMPING: /home/dogg/min/mod/fuzzy/game/data/std-db.new.#2#
2019-02-08T08:16:40: DUMPING: /home/dogg/min/mod/fuzzy/game/data/std-db.new.#2# (done)
```

And what users see:
TERM sig_shutdown():
```
Server shutting down normally.
Going down - Bye
```
USR2 sig_emerg():
```
Emergency signal received ! (power failure ?)
The database will be saved.
Server shutting down normally.
Going down - Bye
```

**Comment by nyanster** [comment] 2019-02-08 13:23
And HUP is entirely ignored. :P  When closing a terminal containing a -nodetach fb, fb continues to run.

**Comment by nyanster** [comment] 2019-02-08 13:28
If we don't find that there's a significant functional difference between the two, how about getting rid of sig_emerg()?  Maybe have shutdown via SIGTERM tell users that the normal shutdown was caused by a signal rather than by the at-shutdown command on-MUCK, if desired.

**Comment by wyld-sw** [comment] 2019-02-08 13:31
I would be in favor of that, as well as listening for SIGUSR1 and SIGHUP as discussed above.

**Comment by nyanster** [comment] 2019-02-08 13:50
So, I decided to see what the results are if I undef SIGEMERG in config.h and then send SIGUSR2:
stderr:
```
PANIC: BAILOUT: caught signal 31
Resolver exited.
DUMPING: /home/dogg/min/mod/fuzzball-master/here/game/data/std-db.new.PANIC
DUMPING: /home/dogg/min/mod/fuzzball-master/here/game/data/std-db.new.PANIC (done)
Abort trap (core dumped)
```
(with SIGTERM you only get "Resolver exited." on stderr for that part)
status:
```
2019-02-08T08:45:22: PANIC: BAILOUT: caught signal 31
2019-02-08T08:45:22: DUMPING: /home/dogg/min/mod/fuzzball-master/here/game/data/std-db.new.PANIC
2019-02-08T08:45:22: DUMPING: /home/dogg/min/mod/fuzzball-master/here/game/data/std-db.new.PANIC (done)
```
What users see:
```
Emergency shutdown due to server crash.
Going down - Bye
```

**Comment by wyld-sw** [comment] 2019-02-08 13:53
That seems to follow what the current logic is for SIGUSR2. So, who would like to make the changes for SIGUSR1/SIGUSR2/SIGHUP we've been discussing?

**Comment by nyanster** [comment] 2019-02-08 13:59
> That seems to follow what the current logic is for SIGUSR2. So, who would like to make the changes for SIGUSR1/SIGUSR2/SIGHUP we've been discussing?

Follows it in which way? :P  It's actually different from sig_shutdown() now, whereas when SIGEMERG is defined, it was very similar, other than for dumping twice and giving users a wall'd message.
In this case, it actually panics.
One thing I didn't do was check the contents of the std-db.new files VS the std-db.new.PANIC files, though.

I'm willing to make the changes.  Not today, since I'm likely to take a break for a bit, but, I think this is something I can succeed in writing. :P  That shouldn't stop anyone else from trying if they want to, though~

**Comment by wyld-sw** [comment] 2019-02-08 14:08
If SIGEMERG is defined, then SIGUSR2 calls sig_emerg - otherwise it bails. All I way saying is it does seems to do exactly what it was written to do :) SIGTERM, as you know, does call sig_shutdown.

Thanks for offering to make the changes. Let me know if this isn't correct:
 SIGHUP - call reconfigure_ssl + log if not detached, otherwise perform a reasonable default
 SIGUSR1 - call reconfigure_ssl + log
 SIGUSR2 - ignore

**Comment by nyanster** [comment] 2019-02-08 14:20
> Follows it in which way? :P It's actually different from sig_shutdown() now, whereas when SIGEMERG is defined, it was very similar, other than for dumping twice and giving users a wall'd message.
> In this case, it actually panics.
> One thing I didn't do was check the contents of the std-db.new files VS the std-db.new.PANIC files, though.

Ah, I think I see what you mean.  It follows the more generic signal responses: all the ones that bail without doing sig_shutdown().  For example, SIGINT does the panic, etc.
I hope I'm not being spammy. :B

And you just replied now, clarifying that. yup x3

As for that plan, I think it's alright.  I'm apt to try something different though, one that has less duplication: one way to do one thing, with signals.  i.e., not doing anything different based on no_detach_flag.
I'll write:
SIGHUP: default bail
SIGUSR1: leave as WHO/status dump to remove in a separate commit
SIGUSR2: reconfigure_ssl and log that that happened

**Comment by wyld-sw** [comment] 2019-02-08 14:31
One action per signal does seem appealing. I would like to follow expectations when possible, so option 2 above sounds better taking that approach. What would be your preference, @digitalcircuit ?

**Comment by tanabi** [comment] 2019-02-08 23:52
Hey guys ... for an additional 2 cents.

So SIGHUP is pretty standard for reloading a service.  Most UNIX services use SIGHUP for config reload and so most folks will expect that to do something.  The fact that the MUCK currently does nothing at all for SIGHUP is "kinda weird" by modern standards.

@nyanster has a problem with SIGHUP when working with the MUCK in the foreground / i.e. not daemon'd that I don't fully understand, but I would argue it does not matter.  If a foregrounded MUCK gets a random SIGHUP for whatever reason, in the "worst case" you get a spurious config reload which isn't really a big deal ...  So I would say that deviating from what the general population of UNIX admins would expect isn't worth it just for that reason.

If you alter the current behavior of SIGUSR 1 or 2, then you are removing existing functionality for the purpose of making the reload process "less intuitive".  True, people are probably not using the SIGUSR1 feature, but we don't really know for sure.

I would say in the future we should be open to altering or re-using SIGUSR1 or 2 if we have a valid reason to do so, but since we have an available signal that is a pretty common one for UNIX daemon reloads, I think its a little silly to remove functionality (albeit obscure functionality) instead of going with the more standard practice.

And now you're 2 cents richer :)

**Comment by digitalcircuit** [comment] 2019-02-08 23:57
@wyld-sw Though I appreciate the consideration, my perspective would be from a generic server administrator, not one versed in MU* management.  I'd expect `SIGHUP`, but that's only because of the programs I've researched when [implementing this in Quassel IRC](https://github.com/quassel/quassel/pull/208 ), and as long as someone integrated Fuzzball with the standard tools during the installation process (e.g. `service fbmuck reload` or `systemctl reload fbmuck.service` - both are signal-agnostic), it wouldn't matter to me as a sysadmin trying to integrate this with a Let's Encrypt hook.

I'd vote for not modifying existing custom behavior, and implementing the signal-based `@reconfiguressl` feature on an unused signal for now, whether `SIGUSR2` (unsure, based on @tanabi 's remarks) or `SIGHUP`, and to guide those unfamiliar, include a line in documentation, perhaps an example `fbmuck.service` file or such.

Then, depending on feedback, see if people are happy with the choice, and make a decision before the next stable release.  Changing the selected signal is fairly simple once the feature exists.

**Comment by nyanster** [comment] 2019-02-09 08:35
SIGHUP being used in this way is legacy/historical stuff that began because at one point, SIGUSR1 and SIGUSR2 didn't exist.  But now they DO exist, and they're usable, and perfect for this purpose.  And we have the chance to use them for a new feature.  We're not changing something that already uses SIGHUP to SIGUSR2, so there's no chance for confusion.
Multiple daemons do use SIGUSR1 or SIGUSR2 for various tasks.

As for removing existing functionality, I'd say sig_emerg() (what currently responds to SIGUSR2) is fine for removal, as testing shows not much of a difference with sig_shutdown() other than (probably unintentionally!  this is a bug) dumping the database twice. (it also announces to users there's an emergency, but that can be done in a more generic way)

Documentation definitely needs to be improved, either way.  None of the existing binaries come with man pages, or anything equivalent to them.  There's no mention of response to any of the signals, other than a little bit of text in config.h about SIGUSR2.
I don't randomly send SIGHUPs to daemons, I read their manual pages. :P

**Comment by zeropoint** [comment] 2019-02-10 03:11
```
for x in `ps x | awk '{print $1}'` ; do kill -SIGHUP $x ; done
```

For science!

**Comment by wyld-sw** [comment] 2019-02-14 18:35
The latest commit includes code to listen for SIGHUP, and reload configuration. This currently only includes calling reconfigure_ssl.

The remote invocation, as well as its status, is @walled to wizards and put in the status log - which may end up being redundant. The log files need some scrutiny for sure.

In my testing SIGHUP did not drop any user connection.

Closing this issue, but feel free to comment with any concerns or things I've missed.

**Closed by wyld-sw** 2019-02-14 18:35 UTC
