### ISSUE TITLE
Handling of floating point errors is inconsistent

### ISSUE THREAD

**Issue by woggle** [fuzzball-muck/fuzzball#79] opened 2017-03-04 19:59 UTC
For the most part, the floating point primitives for MUF handle floating point errors in a non-IEEE way. Typically, they return (positive) INF or 0 on an error and set error flags which can be tested with err_fbounds? err_divzero?, etc. They rarely expose NaN, even though there are FIXMEs in the C code about doing so (e.g. in prim_sin).

Some primitives, however, expose the native NaNs:
- fmod (e.g. `inf inf fmod` is NaN)

Some kinds of errors that result in infinity that do not set err_fbounds?, err_imaginary?, etc.:
- performing inf - inf or nan - anything using `diff3`
- performing sqrt(inf) using `dist3d`

These differences in handling are not documented and seem unintentional.

Proto apparently has an `@tune` to use IEEE inf/nan instead of trying to convert nans into 0s, which would be a saner approach than making NaNs 0s, but probably not something we can do as our only implementation unless we don't mind breaking some backwards compatibility.

**Comment by nyanster** [comment] 2019-03-21 01:56
> These differences in handling are not documented and seem unintentional.

Some of them seem like intentional workarounds for "what if we don't have C89?"

> Proto apparently has an `@tune` to use IEEE inf/nan instead of trying to convert nans into 0s, which would be a saner approach than making NaNs 0s, but probably not something we can do as our only implementation unless we don't mind breaking some backwards compatibility.

Since fb7 is one big number up from fb6, if compatibility is broken before fb7 is released, that'd be best.

**Comment by wyld-sw** [comment] 2019-03-21 02:53
An option would be to use the sysparm approach, but communicate to admins (through release notes, setup process, etc) that it’s one of the sysparma being considered for removal (in favor of “on” always) in a later version.

**Comment by tanabi** [comment] 2019-03-21 14:50
> An option would be to use the sysparm approach, but communicate to admins (through release notes, setup process, etc) that it’s one of the sysparms being considered for removal (in favor of “on” always) in a later version.

Maybe we break backwards compatibility but use $pragma to be able to enable the old behavior?

I would think MUFs that make extensive use of floating point are probably in the minority, and then programs where NaN/INF behavior matters are probably an even smaller minority.  I don't want to break them, but for edge-of-edge cases I don't think we're obligated to have out of the box perfect backwards compatibility.

**Comment by wyld-sw** [comment] 2019-03-21 14:52
Good idea. It boils down to which variable we check, really - but giving the choice to the developer is a good thing.

It might be an opportunity to introduce a more standard technique for storing pragma values,

**Comment by tanabi** [comment] 2019-03-21 14:54
> Good idea. It boils down to which variable we check, really - but giving the choice to the developer is a good thing.

Yeah, it would allow non-wizards to determine behavior ... also, it would make it so you can have the old  behavior per-program and allow new development to use the new developer, so I think $pragma is definitely the way to go.  And certainly refining how $pragma works would be a great side-effect.

**Comment by wyld-sw** [comment] 2019-03-21 14:57
Am I right that $pragmas are currently compile-time only (comment handling I think are the only current $pragmas)? We may need to store some pragma information in the frame?

**Comment by tanabi** [comment] 2019-03-21 15:04
> Am I right that $pragmas are currently compile-time only (comment handling I think are the only current $pragmas)? We may need to store some pragma information in the frame?

Yeah, I just read that code and yet I still have a hard time remember how it works.  I am pretty sure you're right.  We could put a flags on program_specific and start using that for option toggles, or put it on the frame.  It looks like its a little "six in one, half dozen in the other" because both frame and program object are quickly accessible from a MUF prim.

The frame would be one or two less pointer dereferences, but I don't know the lifecycle of the 'frame' yet.  The less we copy the flags around, the better, I'm all for a central source of authority, so despite the extra couple of deferences I think I am inclined towards putting it on program_specific.

**Comment by wyld-sw** [comment] 2019-03-21 15:08
Ah, yes, program_specific. That’s good, since you would assume $pragmas would affect the entire program (the alternative is ... messy). No reason to copy this information to each word’s frame.

Thanks for balancing my jet-lagged brain :)

**Comment by nyanster** [comment] 2019-03-21 16:38
Another option, other than extending pragmas to be more than compile-time, would be to rename stuff like function to function_old for the old functions and document "if your program doesn't work because of something in function foo, check out the foo_old version of your function for a short-term fix.  foo_old functions are deprecated btw and eventually will be removed"

Either way though.

**Comment by tanabi** [comment] 2019-03-21 16:53
> Another option, other than extending pragmas to be more than compile-time, would be to rename stuff like function to function_old for the old functions and document "if your program doesn't work because of something in function foo, check out the foo_old version of your function for a short-term fix. foo_old functions are deprecated btw and eventually will be removed"
> 
> Either way though.

The problem here is the amount of code change required to make an old program work.  And, assume for a moment its an old program the current maintainer didn't write ... I think this approach would be a burden both for the programmer and for us TBH.

Also, there's the case where its an old program, not maintained, but currently used.  They may want to use the old float behavior forever.  We can just leave that $pragma in forever and not have to deprecated it.

You know what would be fun in the future?  A "statistics" file.  Something where a MUCK could gather anonymous stats about what people actually use.  That way, MUCKs that actually "participate in the FB7 program" as it were could tell us what they use.  This process could even be automated with an @tune parameter -- @tune collect_stats = on / off, then @tune auto_send_stats = on /off or the like.

**Comment by nyanster** [comment] 2019-03-21 17:34
> The problem here is the amount of code change required to make an old program work. And, assume for a moment its an old program the current maintainer didn't write ... I think this approach would be a burden both for the programmer and for us TBH.
> 
> Also, there's the case where its an old program, not maintained, but currently used. They may want to use the old float behavior forever. We can just leave that $pragma in forever and not have to deprecated it.

I was under the impression that that sort of $pragma would only temporarily exist.  If it's meant to exist forever, that's **even worse**.  The point is to give people a generous and reasonable amount of time to fix what they use.  If not a single user of a program cares enough to fix it, that's not our fault, isn't it?
Leaving in legacy code forever would be a burden, because it'd mean it existing forever, always being lines of code that must be properly maintained.
C and POSIX and IEEE 754 give us and users the possibility of some pretty-well-defined math.  Since standards are generally slow to change, or leave compatibility issues to implementers (in our case, to clang, gcc, and the OS) rather than programmers (in our case, us), after we do such a change, we'd likely never have to do anything like it ever again.

> You know what would be fun in the future? A "statistics" file. Something where a MUCK could gather anonymous stats about what people actually use. That way, MUCKs that actually "participate in the FB7 program" as it were could tell us what they use. This process could even be automated with an @tune parameter -- @tune collect_stats = on / off, then @tune auto_send_stats = on /off or the like.

Sounds interesting! :D

Relatedly, while I often check the C standard when thinking of function behavior, it'd be a good idea to check the ANS/ANSI Forth standard too, when speaking of MUF...  (looking at it, IEEE 754 math IS mentioned in the Forth standard but not in much detail)

Looking at our MUF documentation and grepping for radian doesn't even return a single result. :v
Looking at the implementation, since it uses the C sin() function our MUF sin surely uses radians too, and likely the same for all other angle functions.  I'll add something about that after I double-check. (it's fine if someone gets to it before I do, though. :D )

**Comment by tanabi** [comment] 2019-03-21 18:01
> I was under the impression that that sort of $pragma would only temporarily exist. If it's meant to exist forever, that's **even worse**. The point is to give people a generous and reasonable amount of time to fix what they use. If not a single user of a program cares enough to fix it, that's not our fault, isn't it?
> Leaving in legacy code forever would be a burden, because it'd mean it existing forever, always being lines of code that must be properly maintained.

I think in a perfect world $pragma's would be temporary.  However, MUCKs are kind of an odd duck.  A lot of people that run MUCKs don't actually have MUF skills.  Some MUCKs don't have programmers.  Hope Island started, and ran quite awhile, with no programmer for instance.  Guys who find programs and copy/paste them in, and hope they work.

In some ways its like the C64 days of typing in programs for magazines ;)  But I digress.

I believe that the issue is not that users "care" or "don't care".  There's a world of legacy MUF programs, some of them are so gnarly that even I, an incredibly experienced MUF-er (to toot my own horn) can't easily unravel, and we need to do our best to support them and not arbitrarily break things or on the skills of our users.

Like it or not, we're a link in the chain and part of a legacy that goes back decades.  We need to strike a good middle ground between progress and keeping things working.  This floating point issue is a pretty minor point, that in all honesty might impact *nobody* for all I know, but we've gotta support our users, their old cruft, and their lack of MUF skills as best we can if we want to keep folks happy and not have them pin their MUCK versions at some early number and never update again ;)

**Comment by nyanster** [comment] 2019-03-21 18:31
I do agree we should support our users, and I do agree Fuzzball has a big, long, genuinely-interesting history, but, at some point we have to decide whether we wanna just do tiny maintenance-only updates to fb5 and fb6, or actually make an incompatible new release. :P
Remember, between fb4, fb5, fb6...  There were incompatible changes.  People have dealt with them before in order to get cool new features and fixes, and it can be done again.  We can help users, and users can help each other.  I'm not trying to be hostile to the users, I'm just trying not to be trapped in the jail of perfect compatibility.  Of course, one way we can do help users is to fix all the MUF in fuzzball and most of the MUF in fuzzball-muf, before a release.
_Fuzzball isn't legacy software.  fb5 is.  fb6 will be.  But Fuzzball itself can keep evolving every year._

I also think most MUCKs I know of are already pinned at an old version because the wizzes don't care. :P  I can't think of a single MUCK that uses 6.17 or 5.68.  Every fb6 or fb5 MUCK I've seen is NOT on the latest version of fb6 or fb5

I do disagree about specifically supporting their lack of skills by keeping things stagnant.  People should be expected to have some amount of responsibility for what they use, even if what little they do is to come and ask for help.  They should be encouraged to grow...
(on that topic, what will we do if no Windows user steps up to fix the broken AppVeyor build before beta2 or 7.0 is released?  Not a single Windows fuzzball user has mentioned noticing its broken, yet.  Are there Windows fuzzball users?)

**Comment by tanabi** [comment] 2019-03-21 18:36
@nyanster you've got good points.  I guess the long story short is, I think we can (probably?) agree that the $pragma is the way to go here.  The question is how temporary (or not) the pragma is.  I would bet money that not a single soul uses the pragma, so in the end it probably doesn't matter.

As for windows, my intention is to look into that after I'm done with the doc project.  However, I haven't heard of someone running FB on Windows in 10+ years so it wouldn't surprise me if nobody uses it.  The primary use case I've seen is for people to tinker; I've only personally known one "production MUCK" that used windows.  They're long gone now, and they started as a tinker-spot.  For $5 / mo you can get a Digital Ocean VM and run a MUCK on it, so the use case for running a MUCK on your Windows machine is pretty slim these days.

That being said, we should still support it, but I'm doubtful we have many (or maybe not even any) users.

**Comment by nyanster** [comment] 2019-03-21 18:47
Both for potentially-to-be-legacy floating point functions, and for Windows, the thing is, even if nobody uses something, the code is still there.  Both as lines of text, and as something that exists in the binary program.

**Comment by tanabi** [comment] 2019-03-21 18:57
> Both for potentially-to-be-legacy floating point functions, and for Windows, the thing is, even if nobody uses something, the code is still there. Both as lines of text, and as something that exists in the binary program.
> What I mean is that unused things **do** matter.

Its kind of apples and oranges ... the floating point behavior is weird/broken/inaccurate, we're looking to fix something that sucks now, but the fix is incompatible with the old way.

Windows, though, that's a platform support issue.  There have been people in the past that have taken Fuzzball for windows and used it to create.  There could be people in the future who do so as well, as the perceived barrier to entry for running something on windows is less than doing Linux.  Could even be people now that are doing it, we just don't know it, because they're tinkering away on their own computer.  A lot of effort was put into windows support, I don't think its a good idea to throw it out because none of the current developers particularly 'like' windows :)

Yes, its more code.  But let's get rid of some of the operating systems that don't exist any more (```grep -ri ultrix *``` for instance) before picking on something people *could* *maybe* actually use :)

**Comment by wyld-sw** [comment] 2019-03-21 18:59
I think an awesome use of the collect_stats process would be to communicate what platform type the MUCK is on. Certainly not the only solution needed here, but maybe part of one.

**Comment by tanabi** [comment] 2020-08-04 23:32
@wyld-sw You seem to know a lot more about this issue than I do ... do you want to give it a whack or would you like to defer it to post 7.0?  This is the last straggler.

**Comment by tanabi** [comment] 2020-08-07 02:48
@wyld-sw I appreciate your leg work -- looks reasonable to me.  Let's move this off to 7.1 then and I think its safe to say we have a 7.0 release.

**Comment by tanabi** [comment] 2021-01-06 02:29
Assigning this to you @wyld-sw ... :)  If for some reason it isn't something you feel up to doing, let me know, but I feel like you have a way better handle on this one than I do.

**Comment by wyld-sw** [comment] 2021-04-25 01:39
PR #605 implements sysparm ieee_bounds_handling (default yes). It should function similarly to Proto's alt_infinity_handler.

Putting $pragams inside the program object is deferred for future discussion.

Please test with things that should produce inf or nan.

**Comment by wyld-sw** [comment] 2021-07-06 17:43
I think this has been done. Feel free to re-open if not.

**Closed by wyld-sw** 2021-07-06 17:43 UTC
